development:
  adapter: postgresql
  encoding: unicode
  database: tedx-brisbane_development
  min_messages: warning

staging:
  adapter: postgresql
  encoding: unicode
  database: tedx-brisbane_development
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: tedx-brisbane_test
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: tedx-brisbane_production
